---

language: python

python:
  - 2.7

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible==2.1.2.0
  - ansible-galaxy install geerlingguy.nodejs -p ./roles/
  
  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ./roles' > ansible.cfg"

script:
  - cd tests
  - ansible-playbook -i inventory ../playbook_appdev.yml --syntax-check
  - ansible-playbook -i inventory ../playbook_appdev.yml --sudo -vvvv
  
  # appdev-cli install is designed not to be idempotent so it always installs the latest without having to up the version number during development
  - >
    ansible-playbook -i inventory ../playbook_appdev.yml --sudo
    | grep -q 'changed=1.*unreachable=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

sudo: required
group: stable
dist: trusty
os: linux
