---

language: python

python:
  - 2.7

install:
  - pip install ansible==1.9.4
  - ansible-galaxy install geerlingguy.nodejs -p ./roles/
  
  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ./roles' > ansible.cfg"

script:
  - cd tests
  - ansible-playbook -i inventory ../playbook_appdev.yml --syntax-check
  - ansible-playbook -i inventory ../playbook_appdev.yml --sudo -vvvv
  - >
    ansible-playbook -i inventory ../playbook_appdev.yml --sudo
    | grep -q 'changed=0.*unreachable=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
