---

- name: Install AppDev
  hosts: all
  sudo: yes
  vars:
    nodejs_forever: false
    nodejs_npm_global_packages:
      - name: npm
      - name: sails
      - name: appdevdesigns/appdev-cli#develop
  roles:
    - ansible-role-nodejs
  tasks:
    - name: install appdev (localhost)
      sudo: no
      # yes types empty line over and over to accept defaults
      shell: yes '' | appdev install {{ appdev_folder_name }} --develop
      args:
        chdir: "{{ playbook_dir }}/.."
        creates: "{{ appdev_folder_name }}/"
      when: inventory_hostname == 'localhost'

    - name: install appdev (test VM)
      sudo: no
      # yes types empty line over and over to accept defaults
      shell: yes '' | appdev install {{ appdev_folder_name }} --develop
      args:
        creates: "{{ appdev_folder_name }}/"
      when: inventory_hostname != 'localhost'
