---

- name: Setup development environment
  hosts: all
  sudo: yes
  tasks:
    - name: install packages
      apt: name="{{ item }}" state=present
      with_items:
        - git
        - gitg
        - geany
        - chromium-browser
