---

- name: Install MySQL server
  hosts: all
  sudo: yes
  tasks:
    - name: install packages
      apt: name="{{ item }}" state=present
      with_items:
        - python-mysqldb
        - mysql-server

    - name: start the MySQL service
      service:
        name: mysql
        state: started
        enabled: true

    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: create mysql database
      mysql_db:
        name: "{{ mysql_database_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: change mysql default port number
      lineinfile: dest=/etc/mysql/my.cnf regexp="^port" insertafter="^\[mysqld]" line="port = {{ mysql_server_port }}"
      notify: restart mysql

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
